### PR TITLE
Add deb-simple-cd-helper notice to README

### PR DESCRIPTION
**Pull request by paulkramme**
This adds a notice to a tool i wrote to make CD with deb-simple possible.

### CODE REVIEW

**Comment by esell** [comment]
Thanks @paulkramme for the PR. There is actually an issue (#17) for another app that potentially adds functionality to deb-simple. What I'm thinking is I'll close this PR and instead add a section to the README that references both apps, that way I can kill two birds with one stone :).

Sound good?

**Comment by paulkramme** [comment]
From what i can get from the Readme, both projects dont do the same. debpkg
would build the the deb, dscdhelper would only get the api token without
exposing it in the project files or webinterfaces, and would "enter" url,
so it would get pushed to deb-simple. So they are working with each other.

I propose that i will add debdpk's notice to the readme, too, so that you
can merge this.

**Comment by paulkramme** [comment]
@xor-gate Is this acceptable?

**Comment by xor-gate** [comment]
Fine for me! Probably xor-gate/debpkg could integrate the API of deb-simple for pushing packages after creation?

**Comment by paulkramme** [comment]
That would be really cool!

**Comment by xor-gate** [comment]
I have proposed something: https://github.com/esell/deb-simple/issues/22

**Comment by esell** [comment]
@xor-gate, the idea of an API is kind of a cool idea. I'm going to merge this PR and then use #22 to track the API stuff.

**Comment by xor-gate** [comment]
Great!

**Pull request merged**
